### ISSUE TITLE
Steering Group Meetings: really ad-hoc?

### ISSUE THREAD

**Issue by huberfl** [wunderkraut/WunderWay#148]
On http://way.wunder.io/delivering-projects/review-retro-steering you can read that "Steering group meetings are held on an ad-hoc basis." - As I have found it, we usually have them every two sprints at least.
Should we change the text in order to comply with the bi-sprintly mode?

**Comment by huntons** [comment]
Yes, these really are ad-hoc for us. We find that with longer term projects we only need to have steering group meetings when we achieve certain targets. If the PO reports that the project is not on track or there is a significant change then we will hold a steering meeting but otherwise we have them every 1-3 months.

**Comment by huberfl** [comment]
This sounds like a good way to deal with it. We have experienced steerings in the past, which were not very productive, because there was hardly news to discuss and decide.
I would add your explanation to the existing page, @huntons.

**Comment by huntons** [comment]
@huberfl Let's get the PM/Scrummaster experts group kicked off so we can start addressing best practices for project delivery around the group. I'll start this by sending a group mail and asking for a volunteer from each country. Once we have the initial group then we can schedule a hangout and perhaps a meetup in the near future to work out how we deliver, review and improve our processes and approaches.

**Comment by huberfl** [comment]
Alright. Then let's stick to the current description and close this issue "won't fix".
