### ISSUE TITLE
Move the wunderway to http://way.wunder.io/ or another non-UK domain

### ISSUE THREAD

**Issue by lewisnyman** [wunderkraut/WunderWay#21]

**Comment by joesb** [comment]
Prob need to think about including a redirect from http://way.wunder.co.uk/ too (or making a new task for that).

**Comment by lewisnyman** [comment]
@joesb I don't think I have the domain details, do you?

**Comment by joesb** [comment]
Yep @lewisnyman I've got the details for the DNS stuff. I'll dig them out and pass them to you on a PM or or something

**Comment by joesb** [comment]
Redirection is an HTTP task rather than DNS, so I've just set http://way.wunder.co.uk/ to CNAME to  hub.wunder.io, and used the nginx there to redirect way.wunder.co.uk > way.wunder.io

The redirect is set to include the request in it, so e.g.
http://way.wunder.co.uk/how/ » http://way.wunder.io/how/

Job done.
