### ISSUE TITLE
Preparing Development Documentation

### ISSUE THREAD

**Issue by huntons** [wunderkraut/WunderWay#95]
Add pages for creating development documentation

**Comment by james-nesbitt** [comment]
I like to have a "developers orientation" guide, as a google doc in the 30:Development folder of a project.

The purpose of this guide is to immediately orient developers with who is involved in the project, and what tools are being used.  
I also like to have some other developer oriented info in there such as Story D.O.D.  and story delivery process, as well as a quick synopsis of the project and the client.

I add appendixes for very specific instructions for common requests from developers such as:
- more extensive contact list;
- how do I set up my git for this project;
- my fork is busted, what do I do;
- how do I test SASS compiling locally.

The quality of these guides is never 100%, but it gives developers a reference when they are ramping up on the project.

A quick note: the document title always includes the name of the project, and the phrase "developer orientation" so that searching google drive works.

**Comment by CBones** [comment]
This initiative was started by WunderCare during WunderCon - Developer documentation in project repository using markdown format. 
Template is included in https://github.com/wunderkraut/Ansibleref

I started custom module used to automate process https://gitlab.com/cbones/devdocs (template is included too)

**Comment by joesb** [comment]
Yes, I agree with @CBones, having used [MDWiki](http://www.mdwiki.info/) to write documentation for JAC taking a lead from the Ansibleref repo, markdown documentation in the project repo is my preferred approach. MDWiki formatting/display is a really great addition.

@james-nesbitt - totally agree that a 'developers orientation' guide is a key document - we added something similar for JAC and it really helped to get new people orientated with the project quickly. Adding appendices like the ones you listed sound great too. +1 for adding notes on describing that!

**Comment by joesb** [comment]
So, there's a Pull Request for this one now at #123, if someone could review it.
